name: GH pages

on:
    schedule:
    - cron: "0 0 * * *" #runs at 00:00 UTC everyday
    push:
      branches:
      - main
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              
            - name: Setup
              uses: actions/setup-python@v2
              with:
                python-version: 3.8
                
            - name: Run
              run: |
                mkdir public
                python3 cat_treats -f ./public/index.html -r
                
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./public
